"""netbox-sdk — Standalone NetBox REST API client library."""

from __future__ import annotations

__all__ = [
    "__version__",
    # config
    "Config",
    "DEFAULT_PROFILE",
    "DEMO_PROFILE",
    "DEMO_BASE_URL",
    "config_path",
    "cache_dir",
    "load_config",
    "load_profile_config",
    "save_config",
    "save_profile_config",
    "clear_profile_config",
    "normalize_base_url",
    "authorization_header_value",
    "resolved_token",
    "is_runtime_config_complete",
    # client
    "NetBoxApiClient",
    "ApiResponse",
    "RequestError",
    "BulkOperationEntryError",
    "custom_field_write_value",
    "custom_fields_for_write",
    "ConnectionProbe",
    "api",
    "async_api",
    "Api",
    "App",
    "PluginsApp",
    "Endpoint",
    "DetailEndpoint",
    "RODetailEndpoint",
    "ROMultiFormatDetailEndpoint",
    "Record",
    "RecordSet",
    "ContentError",
    "ResponseSizeLimitError",
    "AllocationError",
    "ParameterValidationError",
    "JsonPayloadError",
    "PaginationError",
    "BranchingClient",
    "BranchConflictError",
    "BranchingPluginUnavailableError",
    "BranchJobTimeoutError",
    "ProxboxSyncClient",
    "ProxboxSyncError",
    "ScheduleResult",
    "SseFrame",
    "SyncType",
    "validate_sync_types",
    "typed_api",
    "ReleaseLine",
    "SupportedNetBoxVersion",
    "SUPPORTED_NETBOX_VERSIONS",
    "DEFAULT_NETBOX_VERSION",
    "UnsupportedNetBoxVersionError",
    "release_lines",
    "release_line",
    "describe_supported_versions",
    "latest_stable_line",
    "TypedRequestValidationError",
    "TypedResponseValidationError",
    # http_cache
    "HttpCacheStore",
    "CachePolicy",
    "CacheEntry",
    "build_cache_key",
    # schema
    "SchemaIndex",
    "Operation",
    "ResourcePaths",
    "FilterParam",
    "parse_group_resource",
    "load_openapi_schema",
    "build_schema_index",
    "fetch_schema_for_client",
    "SchemaDocumentFrozenError",
    "freeze_document",
    "InvalidLiveSchemaError",
    "requested_netbox_version",
    "bundled_index",
    "detect_release_line",
    "resolve_index",
    "serialize_capabilities",
    "serialize_filter",
    "serialize_groups",
    "serialize_operation",
    "serialize_resource_description",
    "serialize_resources",
    # services
    "ResolvedRequest",
    "resolve_dynamic_request",
    "run_dynamic_command",
    "parse_header_pairs",
    "parse_key_value_pairs",
    "load_json_payload",
    "ACTION_METHOD_MAP",
    # plugin_discovery
    "DiscoveredResource",
    "discover_object_type_resources",
    "discover_plugin_resource_paths",
    "discover_plugin_resources",
    "discover_runtime_resources",
    "enrich_schema_index_with_runtime_resources",
    # plugin_bridge
    "BRIDGE_SCHEMA_VERSION",
    "PluginBridgeAdvertisement",
    "PluginBridgeError",
    "PluginManifest",
    "PluginManifestCatalog",
    "PluginManifestProblem",
    "PluginTool",
    "PluginToolAnnotations",
    "discover_plugin_manifests",
    "plugin_arguments_to_query",
    "parse_plugin_tool_response_document",
    "plugin_tool_request_path",
    "validate_plugin_tool_arguments",
    "validate_plugin_tool_response",
    "validate_plugin_tool_response_document",
]

__version__ = "0.0.12rc3"

from netbox_sdk.branching import (
    BranchConflictError,
    BranchingClient,
    BranchingPluginUnavailableError,
    BranchJobTimeoutError,
)
from netbox_sdk.client import ApiResponse, ConnectionProbe, NetBoxApiClient
from netbox_sdk.config import (
    DEFAULT_PROFILE,
    DEMO_BASE_URL,
    DEMO_PROFILE,
    Config,
    authorization_header_value,
    cache_dir,
    clear_profile_config,
    config_path,
    is_runtime_config_complete,
    load_config,
    load_profile_config,
    normalize_base_url,
    resolved_token,
    save_config,
    save_profile_config,
)
from netbox_sdk.custom_fields import custom_field_write_value, custom_fields_for_write
from netbox_sdk.exceptions import (
    AllocationError,
    BulkOperationEntryError,
    ContentError,
    JsonPayloadError,
    PaginationError,
    ParameterValidationError,
    RequestError,
    ResponseSizeLimitError,
)
from netbox_sdk.facade import (
    Api,
    App,
    DetailEndpoint,
    Endpoint,
    PluginsApp,
    Record,
    RecordSet,
    RODetailEndpoint,
    ROMultiFormatDetailEndpoint,
    api,
    async_api,
)
from netbox_sdk.http_cache import CacheEntry, CachePolicy, HttpCacheStore, build_cache_key
from netbox_sdk.introspection import (
    serialize_capabilities,
    serialize_filter,
    serialize_groups,
    serialize_operation,
    serialize_resource_description,
    serialize_resources,
)
from netbox_sdk.plugin_bridge import (
    BRIDGE_SCHEMA_VERSION,
    PluginBridgeAdvertisement,
    PluginBridgeError,
    PluginManifest,
    PluginManifestCatalog,
    PluginManifestProblem,
    PluginTool,
    PluginToolAnnotations,
    discover_plugin_manifests,
    parse_plugin_tool_response_document,
    plugin_arguments_to_query,
    plugin_tool_request_path,
    validate_plugin_tool_arguments,
    validate_plugin_tool_response,
    validate_plugin_tool_response_document,
)
from netbox_sdk.plugin_discovery import (
    DiscoveredResource,
    discover_object_type_resources,
    discover_plugin_resource_paths,
    discover_plugin_resources,
    discover_runtime_resources,
    enrich_schema_index_with_runtime_resources,
)
from netbox_sdk.proxbox_sync import (
    ProxboxSyncClient,
    ProxboxSyncError,
    ScheduleResult,
    SseFrame,
    SyncType,
    validate_sync_types,
)
from netbox_sdk.schema import (
    FilterParam,
    Operation,
    ResourcePaths,
    SchemaDocumentFrozenError,
    SchemaIndex,
    build_schema_index,
    fetch_schema_for_client,
    freeze_document,
    load_openapi_schema,
    parse_group_resource,
)
from netbox_sdk.schema_resolution import (
    InvalidLiveSchemaError,
    bundled_index,
    detect_release_line,
    requested_netbox_version,
    resolve_index,
)
from netbox_sdk.typed_api import typed_api
from netbox_sdk.typed_runtime import TypedRequestValidationError, TypedResponseValidationError
from netbox_sdk.versioning import (
    DEFAULT_NETBOX_VERSION,
    SUPPORTED_NETBOX_VERSIONS,
    ReleaseLine,
    SupportedNetBoxVersion,
    UnsupportedNetBoxVersionError,
    describe_supported_versions,
    latest_stable_line,
    release_line,
    release_lines,
)

from netbox_sdk.services import (  # isort: skip
    ACTION_METHOD_MAP,
    ResolvedRequest,
    load_json_payload,
    parse_header_pairs,
    parse_key_value_pairs,
    resolve_dynamic_request,
    run_dynamic_command,
)
